'use strict';

// English text for the window. Each leaf is looked up as "ui.<path>" in the
// active locale, so a translation mirrors this shape and anything it leaves out
// falls back to the sentence written here rather than to a key.
//
// Task titles and descriptions are not here: they live in the task manifests,
// because the command line shows them too.

module.exports = {
  // Shared controls
  run: 'Run',
  running: 'Working…',
  cancel: 'Cancel',
  proceed: 'Continue',
  choose: 'Choose…',
  clear: 'Clear',
  copyCommand: 'Copy command',
  copied: 'Copied',
  revealInFinder: 'Show in Finder',
  resultTitle: 'Done',
  language: 'Language',
  itemsMore: 'and {count} more',
  selectAll: 'Select all',
  selectNone: 'Clear selection',
  noOptions: 'Nothing to choose from.',
  pickNone: 'None selected',
  dropHint: 'Drop files here, or use Choose.',
  kindCache: 'Rebuilt automatically',
  kindToolchain: 'Needs reinstalling',
  undo: 'Undo',
  options: 'Options',
  moveToTrash: 'Move to Trash',
  trashNote: 'Everything goes to the Trash, so you can undo this from Recent cleanups.',

  nav: {
    archive: 'Archive',
    disk: 'Disk Cleanup',
    apps: 'Applications',
    power: 'Power',
    other: 'More',
  },

  activity: {
    title: 'Activity',
    empty: 'Runs appear here as they happen, including ones started from the terminal, a Finder quick action or an agent.',
    raw: 'Raw events',
    clear: 'Clear',
    recent: 'Show recent runs',
    none: 'No runs recorded yet.',
    status: { ok: 'Done', partial: 'Partly done', error: 'Failed', needs_confirm: 'Awaiting confirmation', running: 'Running' },
  },

  toast: {
    running: '{task}…',
    done: '{task} finished',
    cancelled: 'Cancelled',
  },

  archive: {
    subtitle: 'Make zip files that open cleanly on Windows, and unpack archives whose file names arrived garbled.',
    dropTitle: 'Drop files or folders here',
    dropBody: 'Zip files can be extracted or checked. Anything else is compressed.',
    clearAll: 'Clear all',
    remove: 'Remove',
    itemsSelected: '{count} items selected',
    zipsSelected: '{count} zip files selected',
    compress: 'Compress',
    extract: 'Extract',
    inspect: 'Check',
    compressHint: 'File names are stored the way Windows expects. Characters Windows cannot use are replaced; the result shows how many, and Activity lists each one.',
    extractHint: 'Names that Windows wrote in an older encoding are recovered. Nothing is written outside the destination folder.',
    inspectHint: 'Shows whether each archive opens cleanly on Windows and how its names are encoded. Nothing is changed.',
    separate: 'Make a separate zip for each item',
    overwriteArchive: 'Replace a zip file of the same name instead of picking a new name',
    overwriteFolder: 'Extract into an existing folder of the same name instead of making a new one',
    excludeWindows: 'Leave out Windows system files (Thumbs.db, desktop.ini)',
    symlinks: 'Symbolic links',
    symlinkStore: 'Keep as links',
    symlinkFollow: 'Include the files they point to',
    symlinkSkip: 'Leave them out',
    encodingTitle: 'Which encoding are the names in?',
    encodingMessage: 'Some names in this archive do not say how they are encoded. Choose the option whose sample names read correctly.',
    encodingAccept: 'Extract',
    verdictOk: 'Opens cleanly on Windows',
    verdictBad: 'Will cause problems on Windows',
    items: 'Items',
    nonAscii: 'Names with non-English characters',
    encoding: 'Name encoding',
    fixHint: 'Compress the original files again here to fix this.',
    problem: {
      MISSING_UTF8_FLAG: '{count} names have no encoding mark, so Windows reads them in its own language setting and they may come out garbled.',
      DECOMPOSED_NAMES: '{count} names are stored in the macOS form, so Korean and accented letters appear split apart on Windows.',
      WIN_ILLEGAL_CHAR: '{count} names contain characters or reserved words Windows cannot use.',
      PATH_ESCAPE: '{count} items point outside the folder they would be extracted to.',
    },
  },

  disk: {
    subtitle: 'Free up space held by developer caches and toolchains. Items go to the Trash unless you choose otherwise.',
    total: 'Space you can free',
    measuredAt: 'Measured at {time}',
    notMeasured: 'Measuring sizes…',
    measuring: 'Measuring sizes',
    measure: 'Measure again',
    confirmTitle: 'Clean up {size}?',
    confirmPermanent: 'These items will be deleted right away and cannot be put back.',
    deleteNow: 'Delete Now',
    notFound: 'Not on this Mac',
    absent: '{count} locations are not on this Mac.',
    showAbsent: 'Show',
    hideAbsent: 'Hide',
    permanent: 'Delete right away instead of moving to the Trash. This cannot be undone.',
    clean: 'Clean Up',
    nothingSelected: 'Select what to clean up',
    selection: '{count} selected · {size}',
    recent: 'Recent cleanups',
    noRecent: 'Cleanups you can undo will appear here.',
    recentRow: '{count} items · {size}',
    toolchainTitle: 'Some items have to be reinstalled',
    toolchainMessage: 'These are not rebuilt automatically. You will need to download or set them up again.',
    toolchainAccept: 'Clean Up Anyway',
  },

  apps: {
    subtitle: 'Remove an app together with the settings, caches and data it leaves behind. Everything goes to the Trash and can be put back.',
    search: 'Search',
    count: '{count} apps',
    noMatch: 'No apps match your search.',
    running: 'Running',
    runningNote: 'Quit the app to remove it',
    keepData: 'Keep the app’s settings and data, remove the app only',
    remove: 'Remove',
    nothingSelected: 'Select apps to remove',
    selection: '{count} selected',
    recent: 'Recently removed',
    noRecent: 'Apps you remove will appear here so you can put them back.',
    putBack: 'Put Back',
    confirmTitle: 'Move to the Trash?',
    confirmMessage: 'These items will be moved to the Trash. You can put them back from Recently removed.',
    nameOnly: 'Name match only',
    totalSize: 'Total: {size}',
  },

  power: {
    subtitle: 'Keep the Mac awake through a long build or download, with the lid open or closed.',
    lidState: 'When the lid closes',
    lidSleeps: 'Sleeps',
    lidAwake: 'Stays awake',
    lidRestoreScheduled: 'Switches back automatically',
    idleState: 'Stay awake',
    idleNormal: 'Off',
    idlePrevented: 'On, {minutes} min left',
    displayState: 'Display turns off after',
    displayNever: 'Never',
    minutes: '{minutes} min',
    hours: '{hours} h',
    keepAwakeTitle: 'Stay awake while the lid is open',
    keepAwakeLabel: 'Stay awake',
    keepAwakeBody: 'Stops the Mac from sleeping when idle. Closing the lid still puts it to sleep.',
    keepAwakeActive: 'On until {time}',
    lidTitle: 'Stay awake with the lid closed',
    lidLabel: 'Stay awake with the lid closed',
    lidBody: 'For working on an external display, or letting a job finish with the lid shut. Asks for an administrator password and switches back on its own after the time you choose.',
    lidActive: 'On. Sleep returns automatically.',
    lidWarning: 'Do not put the Mac in a bag while this is on. It can overheat.',
    turnOn: 'Turn On',
    turnOff: 'Turn Off',
    duration: 'For',
  },

  other: {
    subtitle: 'Tools that do not have a screen of their own yet.',
  },
};
